### ISSUE TITLE
Make OfficeHourTable Sortable

### ISSUE THREAD

**Issue by WadeVaresio** [ucsb-cs156-s21/proj-ucsb-cs-las#186] opened 2021-05-11 02:30 UTC
# User Story

As a user I can sort each column in the Courses List table on the Courses List Page so that I can easily sort tutors by certain criteria

# Acceptance Criteria

- [ ] Each column in the Courses List table is sortable.
- [ ] Each column correctly sorts in ascending order
- [ ] Each column correctly sorts in descending order

# Implementation Todos

Front end:
- [ ] Add the sortable feature to each column in the OfficeHourTable component. You may find issue #181 helpful

Back end:
None

Testing:
- [ ] Verify via inspection whether each column correctly sorts.
- [ ] All existing tests pass

**Comment by pconrad** [comment] 2021-05-11 23:48
closing: Duplicate of #180 and/or #181

**Closed by pconrad** 2021-05-11 23:48 UTC
Labels: S21-STARTER, starter
