### ISSUE TITLE
Padding between UI buttons and results table

### ISSUE THREAD

**Issue by jvoucsb** [ucsb-cs156-s21/proj-ucsb-cs-las#99] opened 2021-02-16 20:09 UTC

**Comment by JacquelineMai** [comment] 2021-05-08 10:01
Not clear what pages this was intended for, although there doesn't seem to be any spacing issues right now

**Comment by WadeVaresio** [comment] 2021-05-11 16:09
Closing as issues #188 and #189 address this issue.

**Closed by WadeVaresio** 2021-05-11 16:09 UTC
Labels: question, starter
